[package]
name = "netscan"
version = "0.6.0"
authors = ["shellrow <81893184+shellrow@users.noreply.github.com>"]
edition = "2018"
description = "Cross-platform network scan library"
repository = "https://github.com/shellrow/netscan"
readme = "README.md"
keywords = ["network","security","scan"]
categories = ["network-programming"]
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rayon = "1.5"
rand = "0.8"
default-net = "0.5.0"
pnet_packet = "0.28"
pnet_datalink = "0.28"
socket2 = { version = "0.4", features = ["all"] }
tokio = { version = "1.7.0", features = ["rt", "rt-multi-thread", "net", "time", "macros", "sync"] }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = [ "std" ] }

[dev-dependencies]
ipnet = "2.3"
tokio = { version = "1.7.0", features = ["full"] }