[package]
name = "netscan"
version = "0.2.0"
authors = ["shellrow <81893184+shellrow@users.noreply.github.com>"]
edition = "2018"
description = "Cross-platform network scan library"
repository = "https://github.com/shellrow/netscan"
readme = "README.md"
keywords = ["network","security","scan"]
categories = ["network-programming"]
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rayon = "1.5"
rand = "0.8"
default-net = "0.2.0"
log = "0.4"

[target.'cfg(not(windows))'.dependencies]
pnet = "0.28"

[target.'cfg(target_os = "windows")'.dependencies]
pnet = "0.26"

[dev-dependencies]
ipnet = "2.3"
