[package]
name = "netscan"
version = "0.14.0"
authors = ["shellrow <shellrow@protonmail.com>"]
edition = "2021"
description = "Cross-platform network scan library"
repository = "https://github.com/shellrow/netscan"
readme = "README.md"
keywords = ["network","security","scan"]
categories = ["network-programming"]
license = "MIT"

[dependencies]
rayon = "1.7.0"
rand = "0.8.5"
default-net = "0.15.0"
pnet_packet = "0.33.0"
pnet_datalink = "0.33.0"
socket2 = { version = "0.5.3", features = ["all"] }
async-io = { version = "1.13.0", optional = true }
futures = {version = "0.3.28", features = ["executor", "thread-pool"],  optional = true}
futures-lite = {version = "1.13.0", optional = true}
netscan-os = { path = "netscan-os", version = "0.14.0", optional = true }
netscan-service = { path = "netscan-service", version = "0.14.0", optional = true }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = [ "std" ] }

[dev-dependencies]
ipnet = "2.7.2"
dns-lookup = "2.0.2"

[features]
async = ["async-io", "futures", "futures-lite"]
service = ["netscan-service"]
os = ["netscan-os"]
full = ["async", "service", "os"]
default = ["async"]

[lib]
name = "netscan"

[[example]]
name = "port_scan"
path = "examples/port_scan.rs"

[[example]]
name = "host_scan"
path = "examples/host_scan.rs"

[[example]]
name = "async_port_scan"
path = "examples/async_port_scan.rs"
required-features = ["async"]

[[example]]
name = "async_host_scan"
path = "examples/async_host_scan.rs"
required-features = ["async"]

[[example]]
name = "service_detection"
path = "examples/service_detection.rs"
required-features = ["service"]

[[example]]
name = "fingerprinting"
path = "examples/fingerprinting.rs"
required-features = ["os"]
