[package]
name = "netscan"
version = "0.8.0"
authors = ["shellrow <81893184+shellrow@users.noreply.github.com>"]
edition = "2018"
description = "Cross-platform network scan library"
repository = "https://github.com/shellrow/netscan"
readme = "README.md"
keywords = ["network","security","scan"]
categories = ["network-programming"]
license = "MIT"

[dependencies]
rayon = "1.5.1"
rand = "0.8.4"
default-net = "0.5.0"
pnet_packet = "0.28"
pnet_datalink = "0.28"
socket2 = { version = "0.4", features = ["all"] }
tokio = { version = "1.7.0", features = ["rt", "rt-multi-thread", "net", "time", "macros", "sync"], optional = true }
dns-lookup = { version = "1.0", optional = true }
native-tls = { version = "0.2", optional = true }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = [ "std" ] }

[dev-dependencies]
ipnet = "2.3"
tokio = { version = "1.7.0", features = ["full"] }

[features]
async = ["tokio"]
service = ["dns-lookup", "native-tls"]
os = []
full = ["async", "service", "os"]

[lib]
name = "netscan"

[[example]]
name = "port_scan"
path = "examples/port_scan.rs"

[[example]]
name = "host_scan"
path = "examples/host_scan.rs"

[[example]]
name = "async_port_scan"
path = "examples/async_port_scan.rs"
required-features = ["async"]

[[example]]
name = "async_host_scan"
path = "examples/async_host_scan.rs"
required-features = ["async"]

[[example]]
name = "service_detection"
path = "examples/service_detection.rs"
required-features = ["service"]

[[example]]
name = "os_fingerprinting"
path = "examples/os_fingerprinting.rs"
required-features = ["os"]
