[package]
name = "netscan-service"
version = "0.10.0"
authors = ["shellrow <shellrow@protonmail.com>"]
edition = "2021"
description = "Cross-platform network scan library"
repository = "https://github.com/shellrow/netscan"
readme = "../README.md"
keywords = ["network","security","scan"]
categories = ["network-programming"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.3"
dns-lookup = "1.0.8"
native-tls = "0.2.10"
