[package]
name = "netscan-service"
version = "0.12.0"
authors = ["shellrow <shellrow@protonmail.com>"]
edition = "2021"
description = "Service detection library for netscan"
repository = "https://github.com/shellrow/netscan"
readme = "../README.md"
keywords = ["network","security","scan"]
categories = ["network-programming"]
license = "MIT"

[dependencies]
rayon = "1.5.3"
dns-lookup = "1.0.8"
native-tls = "0.2.10"
